Fix Ruby's send SMS with Twillio docs
open-runtimes/examples pull request #107
Opened 2022-10-21 17:39 UTC by fagiani

This commit fixes copy issues:
- Some places where it should read Ruby and instead was Python
- An incorrect path
- A place where it should read with and instead was without
- There was a warning pointing to replace a value that was set with another name

2022-10-28 15:54 UTC, adityaoberai requested changes
Thanks for the fixes @fagiani 
Just a couple of minor changes that need to be made and then this should be good to go 👍

2022-10-28 15:54 UTC, adityaoberai commented on ruby/send-sms-with-twilio/README.md
> +$ cd ruby/send-sms-with-twillio
```suggestion
$ cd ruby/send-sms-with-twilio
```

2022-10-28 15:54 UTC, adityaoberai commented on ruby/send-sms-with-twilio/README.md
> +A Ruby Cloud Function for sending messages to a phone number using [Twilio API](https://www.twilio.com/docs/usage/api).
```suggestion
A Ruby Cloud Function for sending a message to a phone number using [Twilio API](https://www.twilio.com/docs/usage/api).
```

2022-10-31 16:28 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-10-31 19:22 UTC, adityaoberai approved these changes
LGTM 👍

2022-12-20 23:02 UTC, merged

2022-12-20 23:02 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)