Added a deepgramAudioSummary() Function using PHP
open-runtimes/examples pull request #125
Opened 2022-10-31 05:53 UTC by neelshah2409

A Php Cloud Function for audio summary using [Deepgram API](https://developers.deepgram.com/documentation/).

2022-10-31 05:55 UTC, neelshah2409 commented
Made a PR please review it.
@Meldiron @stnguyen90

2022-10-31 16:15 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-29 10:57 UTC, neelshah2409 commented
Made a PR please review it. @Meldiron @stnguyen90

2023-01-10 00:19 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2023-01-10 00:19 UTC, stnguyen90 commented on php/deepgram-Audio-Summary/Readme.md
> +}
This payload is not valid JSON

2023-01-10 00:19 UTC, stnguyen90 commented on php/deepgram-Audio-Summary/Readme.md
> +$ cd php/deepgram-audio-summary
Please update the folder name to match this.

2023-01-10 00:19 UTC, stnguyen90 commented on php/deepgram-Audio-Summary/Readme.md
> +docker run -p 3000:3000 -e INTERNAL_RUNTIME_KEY=secret-key -e INTERNAL_RUNTIME_ENTRYPOINT=main.py --rm --interactive --tty --volume $PWD/code.tar.gz:/tmp/code.tar.gz:ro openruntimes/php:v2-8.1 sh /us
This is the incorrect command to run this runtime container.

2023-01-10 00:19 UTC, stnguyen90 commented on php/deepgram-Audio-Summary/Readme.md
> +- This example is compatible with PHP 2.8.1. Other versions may work but are not guaranteed to work as they haven't been tested.
Please use the correct version number

```suggestion
- This example is compatible with PHP 8.1. Other versions may work but are not guaranteed to work as they haven't been tested.
```

2023-01-10 00:19 UTC, stnguyen90 commented on php/deepgram-Audio-Summary/index.php
> +?>
This is not the correct way to implement a PHP Open Runtimes Function. Please see how the other examples are structured and be sure to test the function like documented in the readme.

2023-01-19 10:45 UTC, Meldiron approved these changes

2023-01-19 10:46 UTC, Meldiron commented
Thanks for the amazing PR 😇 I have added small changes to fix function structure and readme.
Merging the PR now 🥳

2023-01-19 10:51 UTC, merged