Feat 4468 add python deepgram language detection
open-runtimes/examples pull request #128
Opened 2022-10-31 18:27 UTC by Azanul

Closes https://github.com/appwrite/appwrite/issues/4468

2022-10-31 18:33 UTC, stnguyen90 commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-02 10:13 UTC, adityaoberai requested changes
Function mostly looks good.
Just some minor changes and then it will be good to go.

2022-11-02 10:13 UTC, adityaoberai commented on python/deepgram-language-detection/README.md
> +cd python/deepgram-audio-summary
```suggestion
cd python/deepgram-language-detection
```

2022-11-02 10:13 UTC, adityaoberai commented on python/deepgram-language-detection/main.py
> +    return errorMessage(res, 'Payload must contain fileUrl and DEEPGRAM_API_KEY.')
```suggestion
    return errorMessage(res, 'Request must contain the File URL in the payload and the Deepgram API Key as a variable.')
```

The API Key is technically not a part of the request payload, but a part of the variables, so I recommend the change.

2023-01-19 10:15 UTC, Meldiron approved these changes

2023-01-19 10:16 UTC, Meldiron commented
Thanks for the amazing PR 😇 I have tested it and all works great.
Merging the PR now 🥳

2023-01-19 10:22 UTC, adityaoberai approved these changes

2023-01-19 10:22 UTC, merged