Feat 4466 deepgram language detection using node
open-runtimes/examples pull request #138
Opened 2023-03-05 14:17 UTC by Player256

Fixes ![appwrite/appwrite#4466](https://github.com/appwrite/appwrite/issues/4466)

2023-03-06 12:46 UTC, Player256 commented
@stnguyen90 can you give it a look

2023-06-02 21:35 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2023-06-02 21:35 UTC, stnguyen90 commented on node/deepgram_language_detection/src/index.js
> +  const {apiKey} = JSON.parse(req.variables["DEEPGRAM_API_KEY"]);
You shouldn't need to parse the variable like this 🧐

2023-06-02 21:35 UTC, stnguyen90 commented on node/deepgram_language_detection/src/index.js
> +    });
make sure to `return` after this so execution doesn't continue

2023-06-02 21:35 UTC, stnguyen90 commented on node/deepgram_language_detection/src/index.js
> +    });
make sure to `return` after this so execution doesn't continue

2023-08-02 23:59 UTC, stnguyen90 commented
@Player256, will you be able to address the comments I left?

2023-08-03 07:05 UTC, closed without merging