added files of sendmsg
open-runtimes/examples pull request #28
Opened 2022-10-01 18:36 UTC by itsPriyanshuRaj

2022-10-01 18:59 UTC, Meldiron commented
Linking issue: https://github.com/appwrite/appwrite/issues/3954

2022-10-05 22:31 UTC, stnguyen90 requested changes
@itsPriyanshuRaj Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-05 22:31 UTC, stnguyen90 commented on node/send_msg_using_node/index.js
> +// Include voyage module
would you please put everything in `node/send_message` instead of `node/send_msg_using_node`?

2022-10-05 22:31 UTC, stnguyen90 commented on node/send_msg_using_node/index.js
> +})
It doesn't look like this confirms to the format required by open runtime functions. See an example here: https://github.com/open-runtimes/open-runtimes/blob/main/runtimes/node-16.0/example/index.js

2022-10-05 22:31 UTC, stnguyen90 commented on node/send_msg_using_node/index.js
> +  apiSecret: "81fPXp0J9HbhSC8w"
Make sure to use function variables (`req.variables`) for configurable values like these.

2022-10-05 22:31 UTC, stnguyen90 commented on node/send_msg_using_node/index.js
> +vonage.message.sendSms(from, to, text, (err, responseData) => {
The issue asks for a set of supported channels, request payload, and response. Please make sure to follow the instructions in the [issue](https://github.com/appwrite/appwrite/issues/3954).

2022-10-31 16:15 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-01-17 12:35 UTC, christyjacob4 commented
Hi @itsPriyanshuRaj please address the comments so we can work on getting it merged soon

2023-01-19 13:38 UTC, Meldiron commented
Hey there 👋
We are temporarily closing your PR. Feel free to re-open it when you're ready to start working on it again 😇

2023-01-19 13:38 UTC, closed without merging