feat: add url-shortener example
open-runtimes/examples pull request #35
Opened 2022-10-04 13:26 UTC by MoskalykA

## Closes [#3956](https://github.com/appwrite/appwrite/issues/4186)

![image](https://user-images.githubusercontent.com/100430077/193831195-70c2e355-9f16-4bd9-9f24-5b1d0aa47491.png)

2023-01-10 16:29 UTC, christyjacob4 commented on node/url-shortener/README.md
> +
Please include the curl post request as well

Reference : https://github.com/open-runtimes/examples/blob/main/java/deepgramLanguageDetection/README.md?plain=1#L59-L68

2023-01-10 16:30 UTC, christyjacob4 requested changes
Looks great. One tiny comment

2023-01-10 16:46 UTC, MoskalykA commented
> Looks great. One tiny comment

Good 👍🏻

2023-01-17 12:41 UTC, christyjacob4 approved these changes

2023-01-17 12:41 UTC, merged

2023-01-17 12:41 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)