Added Generate Short URL example in Java
open-runtimes/examples pull request #42
Opened 2022-10-04 22:43 UTC by Pooja444

### Github Issue
[Appwrite-4191](https://github.com/appwrite/appwrite/issues/4191)

## Description

This change will add the example of generating a short URL using Java. The supported providers are [tinyurl, bitly]
This change also adds a README for deploying the code using docker.

## Successful executions

### Successful execution using bitly

<img width="1005" alt="Screen Shot 2022-10-04 at 3 24 00 PM" src="https://user-images.githubusercontent.com/24620969/193941805-0c13e7c2-3caf-4bbb-8666-758ccffc0b42.png">

### Successful execution using tinyurl

<img width="1025" alt="Screen Shot 2022-10-04 at 3 23 35 PM" src="https://user-images.githubusercontent.com/24620969/193941850-4b26ed91-a7c6-4098-80ad-9fcb6b785249.png">

## Errors

### Empty payload error

<img width="975" alt="Screen Shot 2022-10-04 at 3 30 23 PM" src="https://user-images.githubusercontent.com/24620969/193942070-89c70f0b-d15c-454b-b2d0-40b0ac4671b6.png">

### Empty variables error

<img width="992" alt="Screen Shot 2022-10-04 at 3 32 22 PM" src="https://user-images.githubusercontent.com/24620969/193942280-6a9903a0-a47d-4a5a-90c3-45eca5f8697e.png">

### Empty API key error
<img width="1000" alt="Screen Shot 2022-10-04 at 3 33 29 PM" src="https://user-images.githubusercontent.com/24620969/193942330-637e1763-cfe9-4829-93c0-4cbf7372f89d.png">

### No provider error

<img width="991" alt="Screen Shot 2022-10-04 at 3 34 24 PM" src="https://user-images.githubusercontent.com/24620969/193942519-6ceb051a-4a7b-46d0-8af7-8e5bfd7b6bca.png">

### No URL error

<img width="1006" alt="Screen Shot 2022-10-04 at 3 35 52 PM" src="https://user-images.githubusercontent.com/24620969/193942770-a465937a-5266-428c-abb9-ef212f77026c.png">

### Unsupported provider error

<img width="1018" alt="Screen Shot 2022-10-04 at 3 36 59 PM" src="https://user-images.githubusercontent.com/24620969/193943333-61cc4e1c-dd58-4b33-b1e8-efc483dd9173.png">

### Invalid URL error

<img width="1019" alt="Screen Shot 2022-10-04 at 3 38 20 PM" src="https://user-images.githubusercontent.com/24620969/193943636-9b5fd254-6cbe-4a0c-a7e8-85e36b628e80.png">

2022-10-05 07:20 UTC, Meldiron commented
@Pooja444 , thanks for the PR! 🤯 Please give us some time to review it.

2022-10-07 16:53 UTC, Meldiron requested changes
Great quality of Java code! 🤯 I left my review, a few small things need to be changed, but other than that, amazing PR. Once my PRs are addressed, I can mark this approved.

2022-10-07 16:53 UTC, Meldiron commented on java/short_url_generator/README.md
> +_Example input:_
Let's please have one more example input with provider `bitly` so others can see what exact name they can use for provider.

2022-10-07 16:53 UTC, Meldiron commented on java/short_url_generator/README.md
> +_Example output:_
Let's please have one more output example where`success`  is `false`, and there is a `message`.

2022-10-07 16:53 UTC, Meldiron commented on java/short_url_generator/README.md
> +**apiKey** - This must be passed within 'variables' section of the request. This API key would be the access token used by the provider for generating a short URL.
Let's please separate this into 2 API keys - one for Bitly, one for TinyURL. That will allow user use both at the same time.

2022-10-07 16:53 UTC, Meldiron commented on java/short_url_generator/Index.java
> +        || variables.get("apiKey").trim().isEmpty()) {
This needs to change a little due to requested change in README. We should have 2 separate variables for each API key - for each provider. Then we only need to validate API key of a specific provider - that would either be `TINYURL_API_KEY` or `BITLY_API_KEY`.

2022-10-07 16:53 UTC, Meldiron commented on java/short_url_generator/README.md
> +**apiKey** - This must be passed within 'variables' section of the request. This API key would be the access token used by the provider for generating a short URL.
We could call them `TINYURL_API_KEY` and  `BITLY_API_KEY`.

2022-10-07 16:53 UTC, Meldiron commented on java/short_url_generator/Index.java
> +    String apiKey = req.getVariables().get("apiKey");
This will need to be changed to either get `TINYURL_API_KEY` or `BITLY_API_KEY`.

2022-10-07 17:27 UTC, Pooja444 commented
@Meldiron thanks a lot for your comments! I have addressed them and made the required changes.

2022-10-07 17:30 UTC, Pooja444 commented
Tested the changes too -

TinyUrl successful execution - 

<img width="1016" alt="Screen Shot 2022-10-07 at 10 20 44 AM" src="https://user-images.githubusercontent.com/24620969/194615847-dd2520bd-ffcd-48a3-9dad-96341859cefa.png">


Bitly successful execution - 

<img width="1023" alt="Screen Shot 2022-10-07 at 10 20 04 AM" src="https://user-images.githubusercontent.com/24620969/194615886-83199294-fd93-4422-8b44-b19f0a39410b.png">


TinyUrl key not passed error -

<img width="1023" alt="Screen Shot 2022-10-07 at 10 21 02 AM" src="https://user-images.githubusercontent.com/24620969/194615920-033974e9-2544-45fb-b428-dc90f4c9388a.png">


Bitly key not passed error -

<img width="1027" alt="Screen Shot 2022-10-07 at 10 22 10 AM" src="https://user-images.githubusercontent.com/24620969/194615952-0ac5dae5-a809-470e-b274-002c6d267463.png">

2022-10-10 07:20 UTC, Meldiron approved these changes
Looks great to me 😇 🎉🎉🎉

2022-10-14 07:10 UTC, christyjacob4 approved these changes

2022-10-14 07:10 UTC, merged

2022-10-14 07:10 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)