Feat: add translate text function
open-runtimes/examples pull request #43
Opened 2022-10-05 00:09 UTC by aknsal

This PR should close [appwrite/appwrite#4142](https://github.com/appwrite/appwrite/issues/4142)

## Description
Implemented `translate text` function using different providers.
Currently the supoorted providers are :
* Google
* AWS
* Azure

## Screenshots

#### Translation using Google
![google_proof](https://user-images.githubusercontent.com/76688923/193952059-a4d664a5-5d58-49a2-84f0-6b4d61afa12d.png)

#### Translation using Azure
![azure_proof](https://user-images.githubusercontent.com/76688923/193952094-2feffa83-fdd4-4855-a350-43e0705a62d0.png)

#### Translation using AWS
![aws_proof](https://user-images.githubusercontent.com/76688923/193952122-89c5e955-aaa1-4b18-845c-e5c227e248b5.png)

2022-10-27 00:06 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-27 00:06 UTC, stnguyen90 commented on node/translate_text/src/index.js
> +      translatedText = await googleProvider(req.payload).catch((e)=>console.log(e));
On error, please makes sure to return an error response as detailed in the issue.

2022-10-31 16:22 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-07 22:24 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-12-20 22:52 UTC, merged

2022-12-20 22:52 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)