added deno code for invoice generator
open-runtimes/examples pull request #46
Opened 2022-10-05 09:33 UTC by camperjett

Signed-off-by: Jaideep Sharma [sharmajaideep1906@gmail.com](mailto:sharmajaideep1906@gmail.com)

Solves: https://github.com/appwrite/appwrite/issues/4089

PS: This PR is submitted for Hacktoberfest'22

2022-10-05 12:26 UTC, PineappleIOnic commented
Hey There 👋
Thanks for the PR! Could you please attach an image to this issue of the function being successfully executed?

2022-10-05 12:59 UTC, camperjett commented
@PineappleIOnic Check it out!

2022-10-16 08:17 UTC, camperjett commented
PTAL 👀 @PineappleIOnic

2022-10-27 00:25 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-27 00:25 UTC, stnguyen90 commented on deno/generate_invoice/README.md
> +Your function is now listening on port `3000`, and you can execute it by sending `POST` request with appropriate authorization headers. To learn more about runtime, you can visit Deno runtime [README
Please try to use the newest image: `openruntimes/deno:v2-1.24`

2022-10-27 00:25 UTC, stnguyen90 commented on .gitignore
> +.vscode
no need to add this. we may want to add .vscode in the future.

2022-10-31 16:21 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-01-09 19:58 UTC, christyjacob4 commented
@camperjett please address the comments

2023-01-19 13:36 UTC, Meldiron commented
Hey there 👋
We are temporarily closing your PR as there has been no activity on it. Feel free to re-open it when you're ready to start working on it again 😇

2023-01-19 13:36 UTC, closed without merging