Add C# send HTTP request
open-runtimes/examples pull request #51
Opened 2022-10-05 16:55 UTC by NiX3r

![image](https://user-images.githubusercontent.com/47360939/194117681-ed969f84-161a-4751-87ad-02927e6d654b.png)
![image](https://user-images.githubusercontent.com/47360939/194117686-80315a4d-5b16-4850-8098-de6aad155f8b.png)

2022-10-05 19:21 UTC, NiX3r commented on csharp/send-http-request/README.md
> +   docker run -e INTERNAL_RUNTIME_ENTRYPOINT=src/mod.ts --rm --interactive --tty --volume $PWD:/usr/code openruntimes/deno:1.14 sh /usr/local/src/build.sh
Updated. Thanks

2022-10-07 16:47 UTC, stnguyen90 requested changes
@NiX3r Thanks for the PR! 🤯 Please give us some time to review it.

2022-10-14 12:21 UTC, NiX3r commented
I've done some changes. If you might look at it. Thanks

2022-10-17 22:27 UTC, stnguyen90 requested changes
I tried running your code, but got nothing back. here's my request:

```
{"url":"https://demo.appwrite.io/v1/locale/countries/eu","method":"GET","headers":{"x-client-version":"1.0.0"},"body":""}
```

and my result:

```json
{
  "$id": "634dd60d193c85582b43",
  "$createdAt": "2022-10-17T22:24:13.103+00:00",
  "$updatedAt": "2022-10-17T22:24:16.081+00:00",
  "$permissions": [
    "read(\"user:634dcaef4e9b627da03c\")"
  ],
  "functionId": "dotnet-send-http",
  "trigger": "http",
  "status": "completed",
  "statusCode": 200,
  "response": "",
  "stdout": "",
  "stderr": "",
  "duration": 0.267728
}
```

2022-10-18 16:00 UTC, gewenyu99 commented on csharp/send-http-request/README.md
> +   docker run -p 3000:3000 -e INTERNAL_RUNTIME_ENTRYPOINT=src/mod.ts -e INTERNAL_RUNTIME_KEY=secret-key --rm --interactive --tty --volume $PWD/code.tar.gz:/tmp/code.tar.gz:ro openruntimes/dotnet:v2-6
Yep :)

2022-10-31 11:28 UTC, adityaoberai requested changes
@NiX3r can you please look into the following error as well?

2022-10-31 11:28 UTC, adityaoberai commented on csharp/send-http-request/Index.cs
> +    }
Can we please add additional checks in the `if` statement to ensure that if it is a `GET` Request (or other types that don't have a request body), then the `body` and `content type` remain `null`?

In order to debug the empty responses from the functions, I moved the `try` block entry further up and received the response: `Cannot send a content-body with this verb-type.`

![image](https://user-images.githubusercontent.com/31401437/198997410-2b807e53-5e24-4af7-a806-74efafa1beff.png)

Removing the `body` and `content_type` properties from the payload solved this issue. However, keeping the `body` as an empty string triggers the error.

2022-10-31 11:33 UTC, adityaoberai commented on csharp/send-http-request/Index.cs
> +    }
```suggestion
    if(!String.IsNullOrEmpty(body))
    {
        request.ContentType = contentType;
        var streamWriter = new StreamWriter(request.GetRequestStream());
        streamWriter.Write(body);
    })
    {
        request.ContentType = contentType;
        var streamWriter = new StreamWriter(request.GetRequestStream());
        streamWriter.Write(body);
    }
```

This should do the trick.

2022-10-31 11:34 UTC, adityaoberai commented on csharp/send-http-request/Index.cs
> +    if(body != null)
```suggestion
    if(!String.IsNullOrEmpty(body))
```
This should do the trick

2022-10-31 11:48 UTC, adityaoberai requested changes
Suggested some changes @NiX3r

2022-10-31 16:20 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-01-09 19:56 UTC, christyjacob4 commented
@NiX3r please address the comments

2023-01-19 13:36 UTC, Meldiron commented
Hey there 👋
We are temporarily closing your PR as there has been no activity on it. Feel free to re-open it when you're ready to start working on it again 😇

2023-01-19 13:36 UTC, closed without merging