Added Translate text implementation using C#
open-runtimes/examples pull request #55
Opened 2022-10-06 09:23 UTC by gagandeepp

Fixes https://github.com/appwrite/appwrite/issues/4149

2022-10-06 09:25 UTC, gagandeepp commented
https://github.com/appwrite/appwrite/issues/4149

2022-10-10 06:43 UTC, Meldiron commented
@gagandeepp , thanks for the PR! 🤯 Please give us some time to review it.

2022-10-22 16:27 UTC, adityaoberai requested changes
@gagandeepp please review the changes mentioned and add a Readme for the function along with screenshots showing that the function works

2022-10-22 16:27 UTC, adityaoberai commented on dotnet/TranslateText/TranslateText.csproj
> +  <ItemGroup>
Since we are using `Newtonsoft.Json`, please remove the item group here

2022-10-22 16:27 UTC, adityaoberai commented on dotnet/TranslateText/Program.cs
> +class Program
The function structure is incorrect and should be as shown in the [.NET Example here in our docs](https://appwrite.io/docs/functions#writingYourOwnFunction)

2022-10-31 16:40 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-01-19 13:38 UTC, Meldiron commented
Hey there 👋
We are temporarily closing your PR as there has been no activity on it. Feel free to re-open it when you're ready to start working on it again 😇

2023-01-19 13:38 UTC, closed without merging