sendHTTPRequest() Function using Python
open-runtimes/examples pull request #56
Opened 2022-10-06 18:34 UTC by dejmedus

Should close appwrite/appwrite#4177

Added sendHTTPRequest function to examples/python/
 
I also changed the path names in the previous python examples so it will be easier to change directories. 
e.x. python/object-detection/README.md used to say ```cd python/convert_phone_number_to_country_name```

success
<img width="1091" alt="postman success" src="https://user-images.githubusercontent.com/59973863/194389064-218dc376-4fc8-43e5-99cd-33728be7d056.png">

failure
<img width="793" alt="postman failure" src="https://user-images.githubusercontent.com/59973863/194389108-29acf0de-7fb4-4cf2-ab32-c1174eab139f.png">

cli/test.py
<img width="854" alt="bash response" src="https://user-images.githubusercontent.com/59973863/194389187-824bc264-ca6b-4022-8c7f-50d2f1f6467e.png">
<img width="1232" alt="python3 test response" src="https://user-images.githubusercontent.com/59973863/194389221-e559c347-a807-4fe1-b41e-e6bc917f56ed.png">

2022-10-22 16:42 UTC, Meldiron requested changes
Amazing PR! 🤩 Let's please address a few small comments in the README file.

2022-10-22 16:42 UTC, Meldiron commented on python/send-http-request/README.md
> +
Let's please add an example of failed output (to showcase what that would look like)

2022-10-22 16:42 UTC, Meldiron commented on python/send-http-request/README.md
> +
Let's please re-add env variable section, and let's mention there are no variables required to run the function.

2022-10-22 17:00 UTC, Meldiron approved these changes
Looks great 🎉

2022-12-20 22:53 UTC, merged

2022-12-20 22:53 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)