Implemented generateWebsiteScreenshot() in dart using Screenly API.
open-runtimes/examples pull request #63
Opened 2022-10-08 11:30 UTC by 35C4n0r

Implemented the function mentioned in https://github.com/appwrite/appwrite/issues/4107

Sample Scareenshots:
Success
![image](https://user-images.githubusercontent.com/70096901/194704795-333fd8ae-1b55-453a-8120-f658dc656e22.png)

Failure

Signed-off-by: 35C4n0r <jaykumar20march@gmail.com>

2022-10-26 08:03 UTC, 35C4n0r commented
@Meldiron this PR is ready for review please check it once.

2022-10-28 00:29 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-28 00:29 UTC, stnguyen90 commented on dart/generate-website-screenshot/lib/main.dart
> +    );
Please return an error response as described in the issue:

```suggestion
    res.json({
      "success": false,
      "message": "Missing Screenly API Key in environment variables",
    });
    return;
```

2022-10-28 00:29 UTC, stnguyen90 commented on dart/generate-website-screenshot/README.md
> +List of environment variables used by this cloud function:
Let's just call these variables instead of environment variables.

2022-10-28 00:29 UTC, stnguyen90 commented on dart/generate-website-screenshot/README.md
> + - This example is compatible with Dart 2.16. Other versions may work but are not guaranteed to work as they haven't been tested. Versions below Dart 2.14 will not work, because Apwrite SDK requires
Would you please remove the leading space?

2022-10-28 00:29 UTC, stnguyen90 commented on dart/generate-website-screenshot/README.md
> +$ cd dart/generate_website_screenshot
Please rename the folder to be `generate_website_screenshot`

2022-10-28 00:29 UTC, stnguyen90 commented on dart/generate-website-screenshot/pubspec.yaml
> +name: website_screenshot
let's name this generate_website_screenshot to match the folder.

2022-10-28 21:36 UTC, stnguyen90 requested changes
Please see comments

2022-10-28 21:36 UTC, stnguyen90 commented on dart/generate-website-screenshot/README.md
> +$ cd dart/generate_website_screenshot
wrong folder name

2022-10-28 21:36 UTC, stnguyen90 commented on dart/generate-website-screenshot/lib/main.dart
> +    throw Exception("Missing parameter url.");
Please use `res.json()` to return a properly structured error response instead of throwing an error. Make sure to return after calling `res.json()`.

2022-10-28 21:36 UTC, stnguyen90 commented on dart/generate-website-screenshot/README.md
> +docker run -p 3000:3000 -e INTERNAL_RUNTIME_KEY=secret-key --rm --interactive --tty --volume $PWD/code.tar.gz:/tmp/code.tar.gz:ro openruntimes/dart:2.16 sh /usr/local/src/start.sh
Please update the docker images to use `openruntimes/dart:v2-2.16`

2022-10-28 21:36 UTC, stnguyen90 commented on dart/generate-website-screenshot/lib/main.dart
> +      "message": "Missing Screenly API Key in environment variables",
Please remove "environment"

```suggestion
      "message": "Missing Screenly API Key in variables",
```

2022-10-28 21:36 UTC, stnguyen90 commented on dart/generate-website-screenshot/lib/main.dart
> +    res.json({"success": false, "message": "Some error occured"});
Let's be a little more descriptive:

```suggestion
    Map<String, dynamic> parsedBody = jsonDecode(response.body);
    final title = parsedBody['title'];
    final message = parsedBody['message'];
    res.json({"success": false, "message": '$title: $message'});
```

2022-10-28 21:37 UTC, stnguyen90 commented on dart/generate-website-screenshot/README.md
> +$ cd dart/generate_giphy_gif
wrong folder name now

2022-10-29 03:36 UTC, 35C4n0r commented
@stnguyen90 there was one more minor change, the service used was "screeenly" not "screenly". I have corrected that in all the files.

2022-10-31 20:20 UTC, stnguyen90 requested changes
Hopefully, the last request! 😬

2022-10-31 20:20 UTC, stnguyen90 commented on dart/generate-website-screenshot/lib/main.dart
> +  Map<String, dynamic> data = jsonDecode(req.payload);
Would you please add error handling here too? If an invalid JSON string is passed for the payload, execution just hangs and then times out:

```shell
$ curl -H "X-Internal-Challenge: secret-key" -H "Content-Type: application/json" -X POST http://localhost:3000/ -d '{"payload": "}"}'
```

and the container logs shows:

```
FormatException: Unexpected character (at character 1)
}
^
 #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:929)
#2      _parseJson (dart:convert-patch/convert_patch.dart:40)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      jsonDecode (dart:convert/json.dart:155)
#6      start (package:generate_website_screenshot/main.dart:5)
#7      main.<anonymous closure>.<anonymous closure> (file:///usr/local/src/server.dart:37)
#8      main.<anonymous closure>.<anonymous closure> (file:///usr/local/src/server.dart:36)
#9      _rootRun (dart:async/zone.dart:1426)
#10     _CustomZone.run (dart:async/zone.dart:1328)
#11     _runZoned (dart:async/zone.dart:1861)
#12     runZonedGuarded (dart:async/zone.dart:1849)
#13     main.<anonymous closure> (file:///usr/local/src/server.dart:35)
<asynchronous suspension>
#14     handleRequest (package:shelf/shelf_io.dart:115)
<asynchronous suspension>
```

2022-11-02 03:24 UTC, 35C4n0r commented
@stnguyen90 sorry for so many errors in the code, i've made the suggested changes please review them once more.

2022-11-02 20:42 UTC, stnguyen90 approved these changes
one tiny minor change, but otherwise, it's beautiful! 🤩

2022-11-02 20:42 UTC, stnguyen90 commented on dart/generate-website-screenshot/README.md
> +    "screenshot": "An internal error occured"
Error should be in `message`, right?:

```suggestion
    "message": "An internal error occured"
```

2022-12-20 22:54 UTC, merged

2022-12-20 22:54 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)