Added generate map function
open-runtimes/examples pull request #65
Opened 2022-10-08 12:59 UTC by partik03

2022-10-11 09:16 UTC, Shivansh-yadav13 commented on python/generate-map/main.py
> +     elif(lng >180  or lng < -180 ):
```suggestion
     elif(lng >180  and lng < -180 ):
```
It should be `and` ig?

2022-10-11 09:20 UTC, Shivansh-yadav13 commented on python/generate-map/main.py
> +     elif(lng >180  or lng < -180 ):
```suggestion
     elif(lng >180  and lng < -180 ):
```
it should be `and` right?

2022-10-13 05:58 UTC, Shivansh-yadav13 commented on python/generate-map/main.py
> +     elif(lng >180  or lng < -180 ):
ah mb

2022-10-13 08:17 UTC, partik03 commented
@Shivansh-yadav13 can you merge this pull request,now??

2022-10-13 08:28 UTC, Shivansh-yadav13 commented
@partik03 I'm just a contributor :smile: , I was just referencing your PR.

2022-10-31 16:23 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-01 20:31 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2022-11-01 20:31 UTC, stnguyen90 commented on python/generate-map/main.py
> +        return error(res,"Nothing to retrieve please check the url")
It would be helpful to provide a more descriptive error message here like something from the API response.

2022-11-01 20:31 UTC, stnguyen90 commented on python/generate-map/main.py
> +        return res.json({"success":True,"image":str})
something might be off with this encoding...I took the `image` part of the result and tried:

```shell
base64 -d -i img.base64 -o img.png
```

but i wasn't able to open the img.png. Were you?

2022-11-01 20:31 UTC, stnguyen90 commented on python/generate-map/main.py
> +            str = byt.decode()
`str` is a std library function. I would avoid overwriting it.

2022-11-01 20:31 UTC, stnguyen90 commented on python/generate-map/main.py
> +        with Image.open(BytesIO(response.content)) as img:
Why do you need this Image library?

2022-11-02 09:12 UTC, adityaoberai commented
Hey @partik03 
Have you had a chance to review the changes recommended earlier on the PR?

2022-11-07 23:00 UTC, stnguyen90 requested changes
Please address the comments and re-request a review when ready.

2023-01-23 07:36 UTC, Meldiron approved these changes

2023-01-23 07:36 UTC, Meldiron commented
Thanks for the amazing PR 😇 I have added small changes to fix base64 encoding and updated documentation.
Merging the PR now 🥳

2023-01-23 07:38 UTC, merged