send-http-request added
open-runtimes/examples pull request #70
Opened 2022-10-09 12:08 UTC by SanjayDevTech

Fixes: [https://github.com/appwrite/appwrite/issues/4181](https://github.com/appwrite/appwrite/issues/4181)

- Implemented function `sendHTTPRequest()` in `kotlin/` folder.
- Manually executed the newly implemented function to ensure it works using openruntime docker image.

2022-10-10 02:24 UTC, abnegate commented
@SanjayDevTech Thanks for the PR 🤯 Please give us some time to review it 🙏

2022-10-31 16:25 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-02 00:12 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

Would you also please add a README like https://github.com/open-runtimes/examples/blob/1ec5fc25cd5ec71615d44b4ae33214e1d320d25b/kotlin/deepgram-transcribe-audio/README.md?

2022-11-02 00:12 UTC, stnguyen90 commented on kotlin/send-http-request/Index.kt
> +                body = if (json["method"].toString() != "GET") json["body"].toString() else null,
I tried testing with:

```json
{"headers": {"Content-Type": "application/json"},"url": "https://jsonplaceholder.typicode.com/posts", "method": "POST", "body": "{\"title\": \"foo\"}"}
```

and

```json
{"headers": {"Content-Type": "application/json"},"url": "https://jsonplaceholder.typicode.com/posts", "method": "POST", "body": {"title": "foo"}}
```

but I'm getting the following error: 

```json
{"success":false,"message":"JSON payload parsing error: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27 path $."}
```

Any idea what could be wrong?

2023-01-22 09:43 UTC, Meldiron commented
Hey there 👋
We are temporarily closing your PR as there has been no activity on it. Feel free to re-open it when you're ready to start working on it again 😇

2023-01-22 09:43 UTC, closed without merging

2023-08-23 13:27 UTC, SanjayDevTech commented
@stnguyen90 Just want to know how to test the functions immediately after the code change?

2023-08-23 13:30 UTC, SanjayDevTech commented
@Meldiron Can you re-open this pr. I can't see any option to reopen. Thanks