added-generate-website-screenshot-example-in-node
open-runtimes/examples pull request #71
Opened 2022-10-09 18:53 UTC by Abhishek-thakur1

Implemented function `generate-website-screenshot` in `node\` folder.

Sample of response is here: 
![Screenshot-demo](https://user-images.githubusercontent.com/65328363/194774435-5ce3f5d5-362b-4504-b970-8b8ae9a5bd91.png)

And generated screenshot: 
![google](https://user-images.githubusercontent.com/65328363/194774473-1e0d61b4-450d-4b7d-a90b-928d614e6114.png)

2022-10-10 07:35 UTC, Meldiron requested changes
Amazing PR 🤩 Left my review.

2022-10-10 07:35 UTC, Meldiron commented on node/generate_website_screenshot/README.md
> +_Example output:_
Let's please add one more output example, one where success is false and there is error `message`.

2022-10-10 14:25 UTC, Abhishek-thakur1 commented on node/generate_website_screenshot/src/index.js
> +    if (checkLink) {
added `try...catch` in `checkLink()` function, when a pass a invalid url then it will respond with the error message.

2022-10-10 14:26 UTC, Abhishek-thakur1 commented on node/generate_website_screenshot/src/index.js
> +        await fs.writeFileSync(`./${domainName}.png`, image, "base64");
Done!

2022-10-10 14:29 UTC, Abhishek-thakur1 commented on node/generate_website_screenshot/src/index.js
> +    if (checkLink) {
@Meldiron

2022-11-01 11:11 UTC, Abhishek-thakur1 commented
Sure

2023-01-22 10:25 UTC, Meldiron commented
I can't seem to run the function, I am getting `curl: (52) Empty reply from server` most likely caused by `selenium-webdriver`. I believe this will be a problem as Open Runtimes Node runtime is based of alpine, which does not have any browser pre-installed.

Can we please update the function and use 3rd party API to generate the screenshot? 🙏

2023-01-22 10:27 UTC, Meldiron commented
Here is example what others have done for the screenshot generation: https://github.com/open-runtimes/examples/pull/52/files#diff-358d33ac90034c1728f12d09ddf798c510ff42501eb456fc2a01cfedf3a94ae9R33

2023-02-23 11:47 UTC, Meldiron commented
Hey there 👋
We are temporarily closing your PR as there has been no activity on it. Feel free to re-open it when you're ready to start working on it again 😇

2023-02-23 11:47 UTC, closed without merging