Updated all the files's req.env ==> req.variables.
open-runtimes/examples pull request #81
Opened 2022-10-13 12:21 UTC by 35C4n0r

I've updated all the files in which ```req.env``` was being used previously to ```req.variables```. I've also remove emojis from some of the files and comments.
Signed-off-by: 35C4n0r <jaykumar20march@gmail.com>

2022-10-14 09:25 UTC, Meldiron requested changes
Hey there 👋 Thanks for the PR. I noticed you missed a few files in PHP:
- object_detection
- generate_giphy_gif
- convert-phone-number-to-country-name

Please update those too, same thing, renaming from `env` to `variables`.

2022-10-14 09:52 UTC, 35C4n0r commented
> Hey there 👋 Thanks for the PR. I noticed you missed a few files in PHP:
> 
> * object_detection
> * generate_giphy_gif
> * convert-phone-number-to-country-name
> 
> Please update those too, same thing, renaming from `env` to `variables`.

@Meldiron thanks for the review, i've made the changes.

2022-10-14 10:52 UTC, Meldiron approved these changes
Looks great 😍

2022-10-14 16:07 UTC, thinkverse commented
> Hey there 👋 Thanks for the PR. I noticed you missed a few files in PHP:
> 
>     * object_detection
> 
>     * generate_giphy_gif
> 
>     * convert-phone-number-to-country-name

I already have two PRs for updating the Giphy (https://github.com/open-runtimes/examples/pull/74) and Object Detection (https://github.com/open-runtimes/examples/pull/75) once. Also, shouldn't the docker runtimes also be updated to `v2` as well?

2022-10-14 16:20 UTC, 35C4n0r commented
> I already have two PRs for updating the Giphy (#74) and Object Detection (#75) once. Also, shouldn't the docker runtimes also be updated to `v2` as well?

@thinkverse for updating docker runtimes to ```v2``` we only need to change the commands provided in the READMEs, right?

2022-10-14 16:23 UTC, thinkverse commented
> updating docker runtimes to `v2` we only need to change the commands provided in the READMEs

That's my assumption yes, @Meldiron could confirm. Since it's the `v2` image tags that use `variables` instead of `env`.

2022-11-03 19:18 UTC, stnguyen90 commented
@35C4n0r, yes please update the readmes except for the ones that would conflict with #74 and #75 🙏🏼

2023-01-19 13:34 UTC, 35C4n0r commented
@stnguyen90 @Meldiron There was a conflict, which has now been resolved. Please review and merge this PR.

2023-01-20 11:33 UTC, Meldiron approved these changes

2023-01-20 13:23 UTC, christyjacob4 approved these changes

2023-01-20 13:28 UTC, thinkverse commented on php/generate_giphy_gif/index.php
> +
```suggestion

```

Remove this leftover space. 👍

2023-01-20 14:35 UTC, Meldiron commented
Thanks for the amazing PR 😇
Merging the PR now 🥳

2023-01-20 14:35 UTC, merged