⚡  Write a deepgramTranscribeVideo() Function using Deno #4476
open-runtimes/examples pull request #93
Opened 2022-10-17 10:52 UTC by Rinshin-Jalal

## Closes [#4476](https://github.com/appwrite/appwrite/issues/4476)

## Description

According to the issue [#4476](https://github.com/appwrite/appwrite/issues/4476) on appwrite,

I created a Python Cloud Function for transcribing video using [Deepgram](https://deepgram.com/)

It can transcribe videos using Deepgram

___

## Screenshots

### 1. Success full response 

![image](https://user-images.githubusercontent.com/88965873/196159418-e00a9f62-fd91-4cf1-9453-803e14fd1d1a.png)

### 2. Error Response - Invalid fileUrl
![image](https://user-images.githubusercontent.com/88965873/196159334-a9cb44ca-2cd1-447e-bce0-c8d50d930b72.png)

## 3. Error Response - Invalid API key

![image](https://user-images.githubusercontent.com/88965873/196159224-14a0bcd4-55e5-4ef6-a654-8f49b8934dc8.png)

2022-10-20 17:23 UTC, vasucp1207 commented
Hey, @Rinshin-Jalal I saw your code as I am also working on the same kind of issue can you please tell me the steps you follow in order to run your deno function? I get some errors while executing the commands.

2022-10-20 17:49 UTC, Rinshin-Jalal commented
hi, @vasucp1207 

Can you show me the error??



2. Enter this function folder and build the code:

```
docker run -e INTERNAL_RUNTIME_ENTRYPOINT=src/mod.ts --rm --interactive --tty --volume $PWD:/usr/code openruntimes/deno:v2-1.21 sh /usr/local/src/build.sh
```

As a result, a `code.tar.gz` file will be generated.

3. Start the Open Runtime:

```
docker run -p 3000:3000 -e INTERNAL_RUNTIME_ENTRYPOINT=src/mod.ts -e INTERNAL_RUNTIME_KEY=secret-key --rm --interactive --tty --volume $PWD/code.tar.gz:/tmp/code.tar.gz:ro openruntimes/deno:v2-1.21 sh /usr/local/src/start.sh
```

- Docker must be installed
- your code must be in the src folder of this terminal command

2022-10-20 18:19 UTC, vasucp1207 commented
Hey, @Rinshin-Jalal even though I try to run the same code as yours and also follow all the steps but still got the same error.


<img width="939" alt="Screenshot 2022-10-20 at 11 48 26 PM" src="https://user-images.githubusercontent.com/85363195/197027293-2c74ec2d-4eec-40dc-ac02-28456c3ab25a.png">

2022-10-20 18:23 UTC, Rinshin-Jalal commented
> Hey, @Rinshin-Jalal even though I try to run the same code as yours and also follow all the steps but still got the same error.
> 
> 
> <img width="939" alt="Screenshot 2022-10-20 at 11 48 26 PM" src="https://user-images.githubusercontent.com/85363195/197027293-2c74ec2d-4eec-40dc-ac02-28456c3ab25a.png">
> 

Oops, I don't know the answer to this, can you ask it in the appwrite discord server

2022-10-31 16:34 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-02 08:10 UTC, Rinshin-Jalal commented
@stnguyen90 Review this

2022-11-09 00:31 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2022-11-23 20:48 UTC, stnguyen90 requested changes
please see my comments.

2022-11-23 20:48 UTC, stnguyen90 commented on deno/deepgram-transcribe-video/src/mod.ts
> +  const APIkey = req.variables["DEEPGRAM_API_KEY"];
best practice for variable names in deno/typescript is to be camel-cased:
```suggestion
  const apiKey = req.variables["DEEPGRAM_API_KEY"];
```

2022-11-23 20:48 UTC, stnguyen90 commented on deno/deepgram-transcribe-video/src/mod.ts
> +  }
you need to make sure to call return or else the rest of the code will still execute.

2022-11-23 20:48 UTC, stnguyen90 commented on deno/deepgram-transcribe-video/src/mod.ts
> +  const fileUrl = JSON.parse(req.payload)["fileUrl"];
Make sure to catch errors. Passing an invalid JSON string for payload results in an unhelpful error:

```shell
curl http://localhost:3000/ -d '{"variables": {},"payload": "{\"filUrl\":\"https://static.deepgram.com/examples/interview_speech-analytics.wav\""}' -H "X-Internal-Challenge: secret-key" -H "Content-Type: application/json"
{
  "stdout": "",
  "stderr": "Code file not found."
}
```

2022-12-09 00:35 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2023-01-09 20:08 UTC, merged

2023-01-09 20:08 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)