feat: deepgram language detection
open-runtimes/examples pull request #94
Opened 2022-10-18 05:51 UTC by Shivansh-yadav13

- ref: https://github.com/appwrite/appwrite/issues/4469

2022-10-25 05:41 UTC, Shivansh-yadav13 commented
@christyjacob4 please your add review

2022-10-31 16:34 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-09 19:19 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2022-11-09 19:19 UTC, stnguyen90 commented on ruby/deepgram-language-detection/index.rb
> +      raise "Payload is invalid."
instead of raising an error, please make sure to call `res.json()` and return an informative error response as defined in the issue.

2022-11-09 19:19 UTC, stnguyen90 commented on ruby/deepgram-language-detection/index.rb
> +  request["Authorization"] = "Token #{req.env["DEEPGRAM_API_KEY"]}"
Make sure to use `req.variables`:

```suggestion
  request["Authorization"] = "Token #{req.variables["DEEPGRAM_API_KEY"]}"
```

2022-11-09 19:19 UTC, stnguyen90 commented on ruby/deepgram-language-detection/index.rb
> +    deepgramData: detected_language
Let's return all the data as we're not sure what part of the response could be helpful for developers:

```suggestion
  res.json({
    success: true,
    deepgramData: parsed_response
```

2023-01-19 13:12 UTC, Meldiron commented
Hey there 👋
We are temporarily closing your PR as there has been no activity on it. Feel free to re-open it when you're ready to start working on it again 😇

2023-01-19 13:12 UTC, closed without merging